"""Update tables

Revision ID: efa9b37f553c
Revises: 1c7e11d2a6ca
Create Date: 2024-02-28 13:48:50.136384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa9b37f553c'
down_revision = '1c7e11d2a6ca'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('news_items') as batch_op:
        batch_op.add_column(sa.Column('feed_id', sa.Integer, sa.ForeignKey('feeds.id')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_news_items_feed_id_feeds'), 'news_items', type_='foreignkey')
    op.drop_column('news_items', 'feed_id')
    # ### end Alembic commands ###
